### ISSUE TITLE
Bot follows everyone who switches voicechanel.

### ISSUE THREAD

**Issue by daniel-san-fried** [Darkside138/DiscordSoundboard#114] opened 2019-08-15 08:50 UTC
Hey there!
I have a question. My bot always follows other servermembers, when the switch to another voice chanel. Not when they disconnect completely, only when they switch from "voicechanel 1" to "voicechanel 2", the bot leaves with them.

My guess is maybe it's related with the "entrance and leave sounds" or the "username_to_join_channel" which I already changed to only my name, left it blank, typed in random things. The problem's still there.
Maybe there is a way to prevent the bot from joining/switching chanels automatically in the first place? Tried that via roles, didn't work.

Does anyone have the same issue or an solution to this? Maybe there is a workaround or a fix. I'm very happy for an answer!

Have a great Day!
Daniel

**Comment by z1g** [comment] 2019-08-22 21:38
If you have entrance sounds for users the bot will join whatever voice channel they join to play that sound.  Even the user is only moving to a different voice channel. If the bot moves from voice channel 1 to voice channel 2 when a user moves it will return to voice channel 1 if a user from that channel requests a sound or another user with an entrance sound joins.

If you want the bot to stay in one voice channel you should create a role on the discord server for the bot and give it only rights to the voice channel you want it to access.

**Comment by Darkside138** [comment] 2019-10-26 16:45
This could also be an issue with the bot being horribly out of date. I'm going to close as I believe this is essentially a duplicate of #112

**Closed by Darkside138** 2019-10-26 16:45 UTC
