### ISSUE TITLE
Cannot find some users by ID or Username

### ISSUE THREAD

**Issue by Strider27** [Darkside138/DiscordSoundboard#169] opened 2022-04-10 12:51 UTC
Seem to be having issues with some users, when I'm trying to assign an entrance or leave sound or request ?userdetails using the User ID or Username, the bot can't seem to find them. I get "Could not find user with id or name: " from the bot.

Works fine with other users however.

**Comment by Darkside138** [comment] 2022-04-10 14:38
Yeah, this will be fixed in the next release. The issue is that the bot currently can only find people that are online and connected to a voice channel.

**Comment by Strider27** [comment] 2022-04-10 14:44
> Yeah, this will be fixed in the next release. The issue is that the bot currently can only find people that are online and connected to a voice channel.

Ok makes sense, at least we have a workaround :)

**Comment by Strider27** [comment] 2022-04-10 17:20
> Yeah, this will be fixed in the next release. The issue is that the bot currently can only find people that are online and connected to a voice channel.

Actually, just tried it again with an online user, same issue.

**Comment by Darkside138** [comment] 2022-04-12 04:04
Release 3.2.1 this is fixed.

**Closed by Darkside138** 2022-04-12 04:04 UTC
