### ISSUE TITLE
If you haven't DMed the bot, you'll get crash upon commands

### ISSUE THREAD

**Issue by DarkKostas** [Darkside138/DiscordSoundboard#65] opened 2017-05-10 22:15 UTC
Trying to send a command like ?help ?list or whatever(except the sound cause the bot doesn't DM you back), you'll get a crash
![untitled](https://cloud.githubusercontent.com/assets/1405072/25923671/500a9320-35e7-11e7-9067-c105ece056fb.jpg)

**Comment by DarkKostas** [comment] 2017-05-10 22:16
After you send the first DM to the bot, all the commands work normally on chat

**Comment by Darkside138** [comment] 2017-10-03 02:48
Could not reproduce in latest BETA version. Closing.

**Closed by Darkside138** 2017-10-03 02:48 UTC
